---
title: "Application essays"
format: gfm
date: last-updated
---

**Applications are due January 15, 5:00 PM EST.**

## Program Info

About the You3 Program
You3  – A Leadership and Management Program for Postdocs is a structured program aimed at filling a critical need in postdoc professional development for current training and future career success. This program was designed by postdocs for postdocs under the guidance of OGPS Leadership. Based on postdoc survey data and pedagogical best practices, this program is structured as eight 1.5-hour weekly modules to develop mastery in three aspects of management and leadership - Yourself, Your Team, and Your Project. The program modules will be facilitated by the OGPS Professional Development team along with U-M campus experts in select module topics. The program will be enriched with effective tools and case-studies to provide learning opportunities for participants while developing a postdoc community through the cohort model.

Read More: https://ogps.med.umich.edu/you3/

Sessions will be held virtually with additional in-person events to foster community-building in this cohort model. All sessions will take place Monday from 12:00 - 1:30 pm on the following dates:

Feb 5, In-person Welcome and Program Overview
Feb 12, Virtual: Identifying your strengths
Feb 19, Virtual: Implicit Bias in team building
Feb 26, Virtual: Time Management
March 4, Virtual: Resource management and Budgeting
March 11, Virtual: Starting your team
March 18, Virtual: Building your team
March 25, Virtual: Communication and Conflict resolution
April 1, In-person: Leadership and Wrap-up celebration

Lunch will be provided during the in-person sessions, and we encourage you to have your lunch during the virtual sessions to best manage your busy schedules!

## Q1

> Tell us your primary motivation to apply for the You3 Program (250 words or less).

> An ideal response would include how the program fits into current challenges you have, future goals, particular skills you’re interested in strengthening, etc. Please share at least a few sentences explaining your interest in joining the program, which will enable the committee to best evaluate your participation.






## Answer to Q1

I want to develop skills in leadership and team management. I hope to start a new job in the near future. In my new position, I expect to lead a team of junior researchers as we work to achieve our goals in biostatistics and human genetics. This role will require me to motivate my team, monitor progress, encourage creativity and problem solving, negotiate with others within and outside my team, and promote team members' development as scientists. While I have extensive training in quantitative and biomedical research skills, I have little format training in many crucial team management skills.

I hope that the You3 program will guide me as I prepare to learn and practice the needed skills.




## Q2 

> Please respond to ONE of the questions below. (250 words or less)
> Please include at least a few sentences responding to the question. This will help us learn more about you.

### 2a

> Tell us about a time when you had a conflict or challenge with a project that did not get solved effectively. With that in mind, what types of skills would you hope to learn from this program that could have helped you approach it differently?


### 2b

> Tell us about a time, currently or in the past, when you have managed a person or people. What do you hope to learn from this program that would expand and improve your management skills and why?
>

### 2c

> Tell us of a time when you struggled in a leadership position. What were the specific challenges? What skills from this course would be helpful and why?

### 2d

> Tell us of a time when you were part of a team or project that was not managed effectively. Share what the issues were and what steps were/could have been taken to improve the experience. What skills would you hope to learn from this program that could have helped you approach it differently?

## Answer to Q2

I wish to answer 2b: "Tell us about a time, currently or in the past, when you have managed a person or people. What do you hope to learn from this program that would expand and improve your management skills and why?".

As a graduate student at University of Wisconsin-Madison, I mentored a senior undergraduate researcher in statistics. Over the course of nine months, he developed a new statistical method for using tweets (from Twitter) to identify social media events. We met regularly to discuss progress and to troubleshoot problems. However, I don't feel that I adequately motivated him in his work. While he completed the project and presented a poster at a conference, I feel that we might have progressed further had we both been more energized to complete the project. At the time, I don't think that I regarded team motivation as my responsibility, but I since have recognized that, to a degree, it is.


