---
toc: false
output: 
  bookdown::pdf_document2:
    number_sections: false
params:
  lastmod: !r lubridate::now()
---

# Goals for fellowship and career

I will develop skills in applied Bayesian statistics for design and analysis of systems genetics 
studies with the goal of cultivating a robust biostatistics research agenda. I earned a Ph.D. 
in applied biostatistics at the University of Wisconsin-Madison. My graduate research culminated in the 
dissertation "Testing pleiotropy vs. separate QTL in multiparental populations" in which I developed and 
implemented a multivariate QTL scan with a linear multivariate mixed effects model. Multiple methodological, 
software, and applied journal articles resulted from this research trajectory. 









Due to prior T32 support for 23 months during graduate school, Boehm now seeks thirteen months of research support. 

## Training goals and objectives

## Doctoral dissertation and other research experience



## Activities planned under this award

