---
title: "Fred Boehm's Activities as Member of the GSA Early Career Scientist Community and Membership Engagement Subcommittee"
toc: true
format: 
    docx: default
    pdf: default
---

## Overview

**Dates of participation: Feb 1, 2020 to January 31, 2022**

**Highlights of activities:**  

- Participated in monthly video meetings of the Subcommittee over 24 months    
- With other committee members (including Adrien Assie, Gavin Rice, and others), organized, facilitated, advertised, and moderated monthly online research seminars that featured early career geneticists  
    - 7 seminars in 2020: https://genetics-gsa.org/career-development/seminars/  
- Completed LMAP course online training with Molly Grisham  
- Participated in regular online Professional Skills Virtual Cafe events organized by Courtney McClure:
    - How not to Overcommit (July 22, 2021)  
    - How to Deal with Advisor Feedback (November 19, 2021)  
- With Kaushal Kumar Bhati and others, brainstormed ideas for genetics podcast creation (my term ended before this activity was fully realized)  


## Fred's application to ASHG Program Committee 

**Term start date: January 1, 2025**

**Term duration: 3 years**

**ASHG Program Committee Mission:**

> The Program Committee is responsible for the scientific content of the Annual Meeting and other meetings sponsored by the Society. Committee meets by conference calls (at least 3) to select the featured symposium program and in person in July to select the abstract-driven program. Committee also meets in person in October/November at the Annual Meeting.

https://www.ashg.org/about/committees/program-committee/


## Position Details

> Position Title: Member, ASHG Program Committee

> Work Location: Primarily remote; two-day in-person meeting in July in Rockville, MD; in-person at fall Annual Meeting.
> Impact/Description: The Program Committee (PC) is responsible for organizing the scientific program of the Annual Meeting. The PC consists of approximately thirty members representing the full breadth of human genetics/genomics research, including social/ethical and education research. Please note that during your tenure, ASHG’s policy does not allow Program Committee members to serve as featured symposium speakers or moderators of featured symposia. You may be a first author on one submitted abstract if there is no one else that could submit or present the scientific work. 
> 
> Position Roles and Responsibilities:
> - Review and program abstracts in your area of expertise (June to July): serve as primary abstract reviewer for 100-200 submitted abstracts, recruit three experts to assist with reviewing abstracts, build Platform and Plenary Sessions from high-scoring abstracts, and invite moderators for Platform Sessions.   
> - Review featured symposium proposals: enter online reviews and comments, attend three to four conference calls (February to March), and communicate with proposers to modify and strengthen proposals.  
> - Meet in person twice per year, once in July for a two-day meeting in Rockville, MD and once at the Annual Meeting. Attendance at these meetings and the entire Annual Meeting is required every year of your 3-year tenure.  
> - Travel expenses are paid by ASHG for the July meeting;  
> - Complimentary registration is provided for the Annual Meeting.  
> - Annual Meeting on-site responsibilities include attending and reporting out on your designated sessions.  
> - Plan other special sessions for the Annual Meeting as needed, such as the Distinguished Speakers Symposium, joint collaborations, the late breaking abstract session, or other sessions as directed by the Board.  
> - Evaluate attendee survey results and suggest improvements for future meetings.  
> - Other duties as needed.  

> Qualifications:
> - Must be a current ASHG member  
> - Must not be an employee or owner of an ineligible company  
> - Interest in shaping content for the ASHG Annual Meeting    
> - Excellent scientific judgment concerning a broad range of genetics research  
> - Ability to keep tight deadlines  
> - Good oral and written communication skills  
> - Interpersonal skills, including tact and diplomacy  

> Commitment:
> - Three-year term; no member may serve more than one consecutive term. Typical service entails 15-20 hours in January-March; 25-30 hours in June-July, plus attendance at two-day in-person meeting in July; and attendance at Annual Meeting. During other periods, typical service is 1-2 hours a month.  

> Benefits:  
> - Helping to shape the future of the field and present new findings
> - Opportunity to engage, network, and exchange ideas with others interested in genetics and genomics research  
> - Contribute to maintaining scientific rigor of material presented at ASHG Annual Meeting  
> - Grow your professional development  
> - Receive a Certificate of Service  
> - List the service on your resume/CV  
> 
> Orientation:  
- A phone conference will discuss the expectations of the members and the role the members will play in different tasks. This is typically scheduled in mid-January.



## Reference form questions

**Please describe the applicant's leadership skills, including his/her previous professional and/or volunteer experience**

Fred served as a member of the Early Career Scientist Community and Membership Engagement (CME) Subcommittee for the Genetics Society of America from February 2020 to January 2022. As a member of the CME subcommittee, Fred participated in monthly video meetings, organized, facilitated, advertised, and moderated monthly online research seminars that featured early career geneticists, and completed a 6-week online training program in Leadership and Management in Action Program with a cohort of about fifteen early career geneticists (https://drive.google.com/file/d/1xp9-gjLDxlrPtHyF4FqTf9_q0-aL47av/view).  

Fred was a reliable and active participant in the CME subcommittee. Despite complications arising from the global covid19 pandemic, he never missed a monthly online meeting in his two years of membership. He met all deadlines for organizing and facilitating the monthly online research seminars, and he was an effective and supportive moderator during the seminars. He communicated effectively while recruiting and coordinating with seminar speakers, and he was a positive and supportive presence in the subcommittee.

His other leadership accomplishments outside GSA, including his roles as Mathcounts coach for middle school students (both in Massachusetts and Wisconsin), founder of a learning center for homeless children, and his ongoing work as a penpal with an economically disadvantaged pre-scientist in Redwood City, demonstrate his commitment to leadership and service in the scientific community.  




**How will the applicant's interests and experience benefit the Board?**

Fred's enthusiasm for his service work, when coupled with his professional dedication to science and development of inclusive and equitable scientific communities, will make him an excellent addition to the ASHG Program Committee. His ability to meet task deadlines and eagerness to connect scientists and future scientists will be a real asset for the ASHG Board. His experience as a member of the GSA CME subcommittee, where he organized and facilitated monthly online research seminars, will be particularly beneficial for the Program Committee. His experience in organizing and facilitating these seminars will be directly applicable to the responsibilities of the Program Committee, which include reviewing and programming abstracts, reviewing featured symposium proposals, and planning other special sessions for the Annual Meeting. His experience in these areas will allow him to contribute to the scientific content of the Annual Meeting in a meaningful way.  





**Other comments**

Fred is perpetually curious as a scientist and as a person. He is always eager to learn and to share his knowledge with others. He is a dedicated and reliable team member, and he is always willing to go the extra mile to help others. He actively undertakes professional development activities to ensure that he is always honing existing skills and developing new skills. I am confident that he will be an excellent addition to the ASHG Program Committee.  

