---
title: "Application: Responses to Survey Questions"
format: gfm
---

## Please describe why you are interested in serving on this committee. 
Word count: 0 / 150

I have three reasons for wanting to serve on the Program committee.

1. **To contribute to the planning and programming for the annual meetings.** I have attended ASHG annual meetings since 2008. While lack of travel funds have limited my recent attendance, I want to contribute to the excellent programming that enables these annual meetings in the years ahead. I wish to take steps to ensure that the annual ASHG meeting continues to be a valuable resource for trainees and other attendees. I also want to ensure that scientists in the ever-growing field of human genetics research feel welcomed and supported at the annual meeting and in the society at all times.  

2. **To access professional development opportunities.** I am interested in the professional development opportunities that come with serving on the Program committee. By serving as a Program committee member, I'll get new perspectives on the details of planning and executing a large scientific meeting. I'll also get to work with extremely talented scientists. In looking at the list of current Program committee members, I recognize many names as leaders in areas of human genetics research that overlap with my research program in genome-wide association studies, genetic epidemiology, and clinical applications of genetics. Working with them in the Program Committee's activities would also give me a chance to build enduring professional relationships. 

**3. To make the society (and its meetings) more welcoming to all human geneticists.** With the growth of the human genetics research community, there is an even greater need to welcome people from backgrounds and career stages that traditionally have been underrepresented in the society and at the annual meeting. As more and more people have opportunities to be scientists, the ASHG needs to adopt practices that make the society and its meetings more welcoming to all human geneticists, regardless of their career stage, background, or identity. I have experience in making classroom instruction settings welcoming to students, and I expect that some of these practices can be adapted to make the annual meeting more welcoming.







## Have you had a significant role in a committee before (ASHG or other)? If yes, please describe your experience. 
Word count: 0 / 150




## ASHG currently programs more than 2,500 poster presentations during the Annual Meeting. How do you think the current format for the poster sessions could be improved in terms of interactivity and the ability of presenters and attendees with similar interests to connect? 
Word count: 0 / 150




## What new trainee activities, programs, or practices could be instituted at the Annual Meeting that would benefit the trainee membership? 
Word count: 0 / 150



