---
title: Leveraging genetically diverse mice to identify host genes that affect tuberculosis susceptibility
author: "Frederick J. Boehm, Clare M. Smith, Christopher M. Sassetti"
date: "9/19/2019"
output:
  pdf_document: default
  html_document: default
  github_document: default
---

One aim of quantitative genetics is to identify genetic variants that influence 
phenotypic variations in disease-related traits. 
Recent development of multiparental mouse populations, 
which incorporate DNA from more than two founders,
has renewed research interest in linkage mapping methods, such as quantitative 
trait locus (QTL) mapping. The *Mycobacterium tuberculosis* research community is 
uniquely positioned to leverage genetic and molecular trait data from diverse 
mouse populations. Multiple research teams have genotyped and phenotyped hundreds 
of mice from the Diversity Outbred and Collaborative Cross populations. We 
develop a QTL mapping framework for integrating genotypic and phenotypic data 
from these two mouse populations. We draw on strengths of each 
population, high recombination counts and high heterozygosity levels in Diversity 
Outbred mice and genetic reproducibility of Collaborative Cross mice, to 
examine tuberculosis susceptibility.


